#
#services:
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: cart-prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./prometheus:/etc/prometheus
#      - prometheus_data:/prometheus
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--storage.tsdb.path=/prometheus'
#    networks:
#      - cart-network
#
#  grafana:
#    image: grafana/grafana:latest
#    container_name: cart-grafana
#    ports:
#      - "3000:3000"
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#    volumes:
#      - grafana_data:/var/lib/grafana
#    networks:
#      - cart-network
#
#volumes:
#  prometheus_data:
#  grafana_data:
#
#networks:
#  cart-network:
#    external: true