#
#services:
#  postgres:
#    image: postgres:15
#    container_name: cart-postgres
#    environment:
#      POSTGRES_DB: cart_service_db
#      POSTGRES_USER: cart_user
#      POSTGRES_PASSWORD: cart_password
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
#    networks:
#      - cart-network
#
#  redis:
#    image: redis:7-alpine
#    container_name: cart-redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#    networks:
#      - cart-network
#
#  pgadmin:
#    image: dpage/pgadmin4:latest
#    container_name: cart-pgadmin
#    environment:
#      PGADMIN_DEFAULT_EMAIL: sungthiut2002@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: stu123123
#    ports:
#      - "5050:80"
#    networks:
#      - cart-network
#    depends_on:
#      - postgres
#
#volumes:
#  postgres_data:
#  redis_data:
#
#networks:
#  cart-network:
#    external: true
