#services:
#  sonarqube:
#    image: sonarqube:10.2-community
#    container_name: cart-sonarqube
#    ports:
#      - "9000:9000"
#    environment:
#      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
#    volumes:
#      - sonarqube_data:/opt/sonarqube/data
#      - sonarqube_extensions:/opt/sonarqube/extensions
#      - sonarqube_logs:/opt/sonarqube/logs
#    networks:
#      - cart-network
#
#  zap:
#    image: ghcr.io/zaproxy/zaproxy:stable
#    container_name: cart-zap
#    ports:
#      - "8080:8080"
#    command: zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=12345
#    networks:
#      - cart-network
#
#  trivy:
#    image: aquasec/trivy:latest
#    container_name: cart-trivy
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ./:/app
#    working_dir: /app
#    networks:
#      - cart-network
#
#volumes:
#  sonarqube_data:
#  sonarqube_extensions:
#  sonarqube_logs:
#
#networks:
#  cart-network:
#    external: true
