server:
  port: 9007

spring:
#  application:
#    name: inventory-service

  # Database Configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/inventory_da2?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


  # Kafka Configuration
  kafka:
#    bootstrap-servers: localhost:19092,localhost:19093,localhost:19094
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:${KAFKA_BROKERS:localhost:9092}}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

    consumer:
      group-id: inventory-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

## Circuit Breaker Configuration
#resilience4j:
#  circuitbreaker:
#    instances:
#      product-service:
#        sliding-window-size: 10
#        failure-rate-threshold: 50
#        wait-duration-in-open-state: 60s
#        permitted-number-of-calls-in-half-open-state: 3
#        automatic-transition-from-open-to-half-open-enabled: true
#      cart-service:
#        sliding-window-size: 10
#        failure-rate-threshold: 50
#        wait-duration-in-open-state: 60s
#        permitted-number-of-calls-in-half-open-state: 3
#        automatic-transition-from-open-to-half-open-enabled: true
#      order-service:
#        sliding-window-size: 10
#        failure-rate-threshold: 50
#        wait-duration-in-open-state: 60s
#        permitted-number-of-calls-in-half-open-state: 3
#        automatic-transition-from-open-to-half-open-enabled: true

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    com.stu.inventory_service: DEBUG
    org.springframework.kafka: INFO
    io.github.resilience4j: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"


  # External services
services:
  product:
    url: http://localhost:9002
  cart:
    url: http://localhost:9003
  order:
      url: http://localhost:9004


app:
  product-service:
    url: ${APP_PRODUCT_SERVICE_URL:http://localhost:9001}
  inventory-service:
    url: ${APP_INVENTORY_SERVICE_URL:http://localhost:9007}
  account-service:
    url: ${APP_ACCOUNT_SERVICE_URL:http://localhost:9003}

#jwt:
#  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

## Eureka configuration
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    enabled: true