server:
  port: 9008

spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:mysql://localhost:3306/cart_da2?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: localhost:19092,localhost:19093,localhost:19094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

    consumer:
      group-id: cart-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"



# Dịch vụ gọi lẫn nhau (api)
app:
  product-service:
    url: http://localhost:9001
  inventory-service:
    url: http://localhost:9007
  account-service:
    url: http://localhost:9003

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.stu.cart_service: INFO  # đúng package phải là 'cart_service' nếu bạn dùng dấu gạch dưới trong package
    com.stu.cart_service.service: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970